version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: ctg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    network_mode: "host"

  ctg-monitor:
    build:
      context: ./CTG_monitor
      dockerfile: Dockerfile
    image: ctg-monitor:latest
    container_name: ctg_monitor_service
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - postgres
volumes:
  postgres_data:
