services:
  postgres:
    image: postgres:15-alpine
    container_name: ctg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: ctg_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  ctg-emulator:
    build:
      context: ./medicine_emulator
      dockerfile: Dockerfile
    image: ctg-emulator:latest
    container_name: ctg_emulator_service
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./medicine_emulator/data:/app/data
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883

  ctg-monitor:
    build:
      context: ./CTG_monitor
      dockerfile: Dockerfile
    image: ctg-monitor:latest
    container_name: ctg_monitor_service
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - postgres
      - mosquitto
    environment:
      # Переопределяем переменные окружения для Docker
      - DB_HOST=ctg_postgres
      - DB_PORT=5432
      - DB_USER=ctg_user
      - DB_PASSWORD=ctd_password
      - DB_NAME=ctg_monitor
      - DB_SSLMODE=disable
      - DB_TIMEZONE=Europe/Moscow
      - MQTT_BROKER=tcp://mosquitto:1883
      - MQTT_CLIENT_ID=ctg_monitor_service
      - MQTT_USERNAME=ctg_mqtt_user
      - MQTT_PASSWORD=ctg_mqtt_password
      - MQTT_QOS=1
      - HTTP_PORT=8080
      - GRPC_PORT=50051
      - LOG_LEVEL=info
      - BUFFER_SIZE=100
      - BUFFER_FLUSH_INTERVAL=10
      - MAX_BUFFER_SIZE=1000

volumes:
  postgres_data: