basePath: /api/v1
definitions:
  handlers.CleanupResponse:
    description: Результат операции очистки зависших сессий
    properties:
      active_sessions:
        description: Количество активных сессий после очистки
        example: 2
        type: integer
      message:
        description: Сообщение о результате
        example: Очистка сессий выполнена
        type: string
    type: object
  handlers.ErrorResponse:
    description: Стандартная структура ответа об ошибке
    properties:
      details:
        description: Дополнительные детали ошибки
        example: field required
        type: string
      error:
        description: Описание ошибки
        example: Неверный формат данных
        type: string
    type: object
  handlers.HealthResponse:
    description: Информация о состоянии и работоспособности сервиса
    properties:
      active_sessions:
        description: Количество активных сессий
        example: 3
        type: integer
      service:
        description: Название сервиса
        example: CTG Monitor
        type: string
      status:
        description: Статус сервиса
        example: healthy
        type: string
      timestamp:
        description: Время проверки
        example: "2023-09-01T10:00:00Z"
        type: string
    type: object
  handlers.SessionRequest:
    description: Данные для создания новой сессии мониторинга
    properties:
      card_id:
        description: UUID медицинской карты пациента
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      device_id:
        description: Идентификатор устройства КТГ
        example: CTG-DEVICE-001
        type: string
    required:
    - card_id
    - device_id
    type: object
  handlers.SessionResponse:
    description: Информация о сессии мониторинга КТГ
    properties:
      card_id:
        description: UUID медицинской карты
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      device_id:
        description: Идентификатор устройства
        example: CTG-DEVICE-001
        type: string
      duration:
        description: Продолжительность в секундах
        example: 5400
        type: integer
      end_time:
        description: Время окончания сессии (если завершена)
        example: "2023-09-01T11:30:00Z"
        type: string
      session_id:
        description: UUID сессии
        example: 550e8400-e29b-41d4-a716-446655440001
        type: string
      start_time:
        description: Время начала сессии
        example: "2023-09-01T10:00:00Z"
        type: string
      status:
        description: Статус сессии
        enum:
        - active
        - stopped
        example: active
        type: string
    type: object
  handlers.SuccessResponse:
    description: Стандартная структура успешного ответа
    properties:
      data:
        description: Дополнительные данные
      message:
        description: Сообщение об успехе
        example: Операция выполнена успешно
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Стандартная структура успешного ответа
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CTG Monitor API
  version: "1.0"
paths:
  /monitoring/cleanup:
    post:
      description: Выполняет очистку зависших и неактивных сессий в системе
      produces:
      - application/json
      responses:
        "200":
          description: Результат очистки
          schema:
            $ref: '#/definitions/handlers.CleanupResponse'
      summary: Очистка зависших сессий
      tags:
      - monitoring
  /monitoring/health:
    get:
      description: Возвращает информацию о текущем состоянии и работоспособности сервиса
        мониторинга КТГ
      produces:
      - application/json
      responses:
        "200":
          description: Состояние сервиса
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Проверка состояния сервиса
      tags:
      - monitoring
  /sessions/start:
    post:
      consumes:
      - application/json
      description: Создает новую сессию мониторинга КТГ для указанной медицинской
        карты и устройства
      parameters:
      - description: Данные для создания сессии
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.SessionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Сессия успешно запущена
          schema:
            allOf:
            - $ref: '#/definitions/handlers.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/handlers.SessionResponse'
              type: object
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "409":
          description: Сессия для устройства уже активна
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Запуск новой сессии мониторинга КТГ
      tags:
      - sessions
  /sessions/stop/{session_id}:
    post:
      description: Завершает указанную активную сессию мониторинга КТГ
      parameters:
      - description: UUID сессии
        format: uuid
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Сессия успешно завершена
          schema:
            allOf:
            - $ref: '#/definitions/handlers.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/handlers.SessionResponse'
              type: object
        "400":
          description: Неверный ID сессии
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Сессия не найдена
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Завершение активной сессии мониторинга
      tags:
      - sessions
swagger: "2.0"
tags:
- description: Управление сессиями мониторинга
  name: sessions
- description: Мониторинг состояния сервиса
  name: monitoring
