# monitoring/prometheus.yml - ИСПРАВЛЕННАЯ ВЕРСИЯ
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'myapp'
    static_configs:
      - targets: ['auth-service:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

# УБЕРИТЕ ЭТУ СЕКЦИЮ - она неправильная
# storage:
#   tsdb:
#     retention.time: 30d
#     retention.size: 10GB
#     wal-compression: true
