server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Сбор логов из Docker контейнеров
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    pipeline_stages:
      # Парсинг JSON логов
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            user_id: user_id
            request_id: request_id
            component: component

      # Установка временной метки
      - timestamp:
          source: time
          format: RFC3339Nano

      # Добавление меток
      - labels:
          level: level
          component: component

  # Сбор системных логов
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

  # Логи приложений из файлов
  - job_name: app_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application
          __path__: /var/log/app/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            severity: level
            message: msg
            trace_id: request_id

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          severity: severity

  # Nginx логи
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/access.log

    pipeline_stages:
      # Парсинг nginx access log
      - regex:
          expression: '^(?P<remote_addr>[\d\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>[^\]]*)\] "(?P<method>[A-Z]+) (?P<request_uri>[^ ]*) HTTP/[^"]*" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'

      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700

      - labels:
          method: method
          status: status
