// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: ctg_simple.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на стриминг
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIds     []string               `protobuf:"bytes,1,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"` // ID устройств для подписки
	DataTypes     []string               `protobuf:"bytes,2,rep,name=data_types,json=dataTypes,proto3" json:"data_types,omitempty"` // Типы данных (fetal_heart_rate, uterine_contractions)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_ctg_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctg_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_ctg_simple_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *StreamRequest) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

// Ответ со стримингом данных КТГ (минимальный)
type CTGDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`                    // Значение (-1 = потеря сигнала)
	TimeSec       float64                `protobuf:"fixed64,4,opt,name=time_sec,json=timeSec,proto3" json:"time_sec,omitempty"` // Время в секундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTGDataResponse) Reset() {
	*x = CTGDataResponse{}
	mi := &file_ctg_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTGDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTGDataResponse) ProtoMessage() {}

func (x *CTGDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctg_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTGDataResponse.ProtoReflect.Descriptor instead.
func (*CTGDataResponse) Descriptor() ([]byte, []int) {
	return file_ctg_simple_proto_rawDescGZIP(), []int{1}
}

func (x *CTGDataResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CTGDataResponse) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *CTGDataResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CTGDataResponse) GetTimeSec() float64 {
	if x != nil {
		return x.TimeSec
	}
	return 0
}

var File_ctg_simple_proto protoreflect.FileDescriptor

const file_ctg_simple_proto_rawDesc = "" +
	"\n" +
	"\x10ctg_simple.proto\x12\x03ctg\"M\n" +
	"\rStreamRequest\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\tR\tdeviceIds\x12\x1d\n" +
	"\n" +
	"data_types\x18\x02 \x03(\tR\tdataTypes\"|\n" +
	"\x0fCTGDataResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x19\n" +
	"\btime_sec\x18\x04 \x01(\x01R\atimeSec2O\n" +
	"\x10CTGStreamService\x12;\n" +
	"\rStreamCTGData\x12\x12.ctg.StreamRequest\x1a\x14.ctg.CTGDataResponse0\x01B\rZ\v./api/protob\x06proto3"

var (
	file_ctg_simple_proto_rawDescOnce sync.Once
	file_ctg_simple_proto_rawDescData []byte
)

func file_ctg_simple_proto_rawDescGZIP() []byte {
	file_ctg_simple_proto_rawDescOnce.Do(func() {
		file_ctg_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctg_simple_proto_rawDesc), len(file_ctg_simple_proto_rawDesc)))
	})
	return file_ctg_simple_proto_rawDescData
}

var file_ctg_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ctg_simple_proto_goTypes = []any{
	(*StreamRequest)(nil),   // 0: ctg.StreamRequest
	(*CTGDataResponse)(nil), // 1: ctg.CTGDataResponse
}
var file_ctg_simple_proto_depIdxs = []int32{
	0, // 0: ctg.CTGStreamService.StreamCTGData:input_type -> ctg.StreamRequest
	1, // 1: ctg.CTGStreamService.StreamCTGData:output_type -> ctg.CTGDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ctg_simple_proto_init() }
func file_ctg_simple_proto_init() {
	if File_ctg_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctg_simple_proto_rawDesc), len(file_ctg_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ctg_simple_proto_goTypes,
		DependencyIndexes: file_ctg_simple_proto_depIdxs,
		MessageInfos:      file_ctg_simple_proto_msgTypes,
	}.Build()
	File_ctg_simple_proto = out.File
	file_ctg_simple_proto_goTypes = nil
	file_ctg_simple_proto_depIdxs = nil
}
