// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Itelma Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ml/features": {
            "post": {
                "description": "Рассчитывает статистические фичи на основе CTG данных пациента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ml"
                ],
                "summary": "Вычисление фичей CTG данных",
                "parameters": [
                    {
                        "description": "Запрос на вычисление фичей",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вычисленные фичи",
                        "schema": {
                            "$ref": "#/definitions/models.FeaturesResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ml/health": {
            "get": {
                "description": "Возвращает статус работы ML сервиса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка состояния ML сервиса",
                "responses": {
                    "200": {
                        "description": "Сервис работает",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ml/predict": {
            "post": {
                "description": "Вычисляет фичи и выполняет ML предсказание состояния плода",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ml"
                ],
                "summary": "Предиктивный анализ CTG данных",
                "parameters": [
                    {
                        "description": "Запрос на предсказание",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результат предсказания",
                        "schema": {
                            "$ref": "#/definitions/models.MLResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "description": "Дополнительные детали",
                    "type": "string",
                    "example": "field validation failed"
                },
                "error": {
                    "description": "Сообщение об ошибке",
                    "type": "string",
                    "example": "validation error"
                }
            }
        },
        "models.FeaturesResponse": {
            "type": "object",
            "properties": {
                "available_windows": {
                    "description": "Доступные временные окна",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "240s",
                        "600s",
                        "900s"
                    ]
                },
                "card_id": {
                    "description": "ID карты пациента",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "features": {
                    "description": "Словарь вычисленных фичей",
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "fs_hz": {
                    "description": "Частота дискретизации",
                    "type": "number",
                    "example": 8
                },
                "t_sec": {
                    "description": "Время анализа в секундах",
                    "type": "integer",
                    "example": 960
                }
            }
        },
        "models.MLRequest": {
            "type": "object",
            "properties": {
                "available_windows": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "card_id": {
                    "type": "string"
                },
                "features": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "fs_hz": {
                    "type": "integer"
                },
                "t_sec": {
                    "type": "integer"
                }
            }
        },
        "models.MLResponse": {
            "type": "object",
            "properties": {
                "card_id": {
                    "type": "string"
                },
                "missing": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ok": {
                    "type": "boolean"
                },
                "ran": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "result": {
                    "type": "object",
                    "additionalProperties": true
                },
                "t_sec": {
                    "type": "integer"
                },
                "ui": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8052",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "ML Service API",
	Description:      "API для предиктивного анализа CTG данных",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
